name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '*.tf'  # Trigger only on changes to .tf files

permissions:
  contents: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to use the latest version of checkout
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~>1.9

      - name: Run Terraform
        env:
          AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
          AZURE_DISPLAY_NAME: ${{ secrets.AZURE_DISPLAY_NAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
        run: |
          az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT

      - name: Terraform Init
        id: tf_init
        run: terraform init
        
      - name: Set up Infracost
        run: |
          curl -sSfL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          infracost --version

      - name: Generate Infracost Estimate
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        run: |
          infracost breakdown --path tfplan --format json --out-file infracost-base.json

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Post Infracost Output
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY}}
        run: |
          infracost diff --path infracost-base.json --format diff > infracost_report.md

      - name: Terraform Apply
        if: steps.tf_init.outcome == 'success'
        run: |
          terraform apply -auto-approve tfplan

      - name: Generate TF Docs
        if: success()
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: .
          output-file: README.md
          template: |-
            <!-- BEGIN_TF_DOCS -->
            # Test Top Line text here
            ## Verify
            # Usage
            {{ .Content }}
            <!-- END_TF_DOCS -->

      - name: Set up Git remote
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit README changes
        if: success()  # This will now run if previous steps are successful
        run: |
          sudo chown -R $USER:$USER .  # Change ownership to the current user
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md infracost_report.md
          git commit -m "Update README with Terraform documentation and Infracost report" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up
        run: |
          terraform destroy -auto-approve
          
