name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '*.tf'  # Trigger only on changes to .tf files

permissions:
  contents: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to use the latest version of checkout
        with:
          repository: actions/checkout
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~>1.9

      - name: Run Terraform
        env:
          AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
          AZURE_DISPLAY_NAME: ${{ secrets.AZURE_DISPLAY_NAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
        run: |
          az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: success()  # Only apply if the plan was successful
        run: |
          terraform apply -auto-approve tfplan

      - name: Generate TF Docs
        if: success()
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: .
          output-file: README.md
          template: |-
            <!-- BEGIN_TF_DOCS -->
            # Test Top Line text here

            ## Verify

            Some text here line 1
            Some text here line 2

            # Usage

            {{ .Content }}
            <!-- END_TF_DOCS -->

      - name: Commit README changes
        if: success() && steps.generate_tf_docs.outputs.updated == 'true'
        run: |
          git config --global user.email "matthew.munsinger@gmail.com"
          git config --global user.name "MMunsinger"
          git add README.md
          git commit -m "Update README with Terraform documentation" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up
        run: |
          terraform destroy -auto-approve
          
