name: Terraform CI/CD

on:
  push:
    branches:
      - main
    #paths:
      - '*.tf'  # Trigger only on changes to .tf files

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~>1.9
      
      - name: terraform-docs-gh-actions
        uses: terraform-docs/gh-actions@v1.2.0

      - name: Run Terraform
        env:
          AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
          AZURE_DISPLAY_NAME: ${{ secrets.AZURE_DISPLAY_NAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
        run: |
          az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }}
  
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: success()  # Only apply if the plan was successful
        run: |
          terraform apply -auto-approve tfplan
        
      - name: Update Readme
        if: success()
        run: |
          terraform-docs markdown . > README.md
      
      # - name: Commit readme changes
      #   if: success()
      #   run: |
      #     git config --local user.name "Github Action"
      #     git config --local user.email "action@github.com"
      #     git add README.md
      #     git commit -m "Update README with Terraform documentation"
      #     git push origin main
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Clean up
      #  if: success()  # Clean up if everything was successful
      #  run: |
      #    terraform destroy -auto-approve
