name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '*.tf'  # Trigger only on changes to .tf files

permissions:
  contents: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~>1.9
      
      - name: Run Terraform
        env:
          AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
          AZURE_DISPLAY_NAME: ${{ secrets.AZURE_DISPLAY_NAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
        run: |
          az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }}
  
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: success()  # Only apply if the plan was successful
        run: |
          terraform apply -auto-approve tfplan
        
      - name: Generate TF Docs
        if: success()
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: .
          output-file: README.md
          template: |-
            <!-- BEGIN_TF_DOCS -->
            # Test Top Line text here

            ## Verify

            Some text here line 1
            Some text here line 2

            # Usage

            {{ .Content }}
            <!-- END_TF_DOCS -->
          indention: 3
          
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }} 

      # - name: Commit readme changes
      #   if: success()
      #   run: |
      #     git config --local user.name "Github Action"
      #     git config --local user.email "action@github.com"
      #     git add README.md
      #     git commit -m "Update README with Terraform documentation"
      #     git push origin
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Clean up
      #  if: success()  # Clean up if everything was successful
      #  run: |
      #    terraform destroy -auto-approve
